//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLOG
    {
        public int ID { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> LOGIN { get; set; }
        public Nullable<System.DateTime> LOGOUT { get; set; }
    }
}
